# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Grpc/Proto/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Temporal\Client\GRPC\ServiceClient:
        class: Temporal\Client\GRPC\ServiceClient
        factory: [null, 'create']
        arguments:
            $address: 'temporal:7233'

    Temporal\Client\WorkflowClient:
        class: Temporal\Client\WorkflowClient
        factory: [null, 'create']
        arguments:
            $serviceClient: '@Temporal\Client\GRPC\ServiceClient'
    
    App\Command\RunTemporalWorkerCommand:
        class: App\Command\RunTemporalWorkerCommand
        arguments:
            $workflows:
                - 'App\Temporal\Order\OrderWorkflow'
            $activities: !tagged_iterator temporal.activity
        tags: ['console.command']

    App\Command\RunSagaCommand:
        class: App\Command\RunSagaCommand
        arguments:
            $workflowClient: '@Temporal\Client\WorkflowClient'
        tags: ['console.command']

    App\Temporal\Order\Activity\CreateOrder:
        class: App\Temporal\Order\Activity\CreateOrder
        tags: [ 'temporal.activity' ]
    
    App\Temporal\Order\Activity\ReserveOrder:
        class: App\Temporal\Order\Activity\ReserveOrder
        tags: [ 'temporal.activity' ]

    App\Temporal\Order\Activity\ChargeOrder:
        class: App\Temporal\Order\Activity\ChargeOrder
        tags: [ 'temporal.activity' ]