<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: order.proto

namespace App\Grpc\Proto\Order;

use Spiral\RoadRunner\GRPC;

interface OrderInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "order.Order";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Request $in
    * @return Response
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Create(GRPC\ContextInterface $ctx, Request $in): Response;
}
