################################################################
# Global config
################################################################
global:
    checkNewVersion: false
    sendAnonymousUsage: false
################################################################
# API and dashboard configuration
################################################################
api:
    dashboard: true
    insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
    docker:
        exposedByDefault: false
    file:
        filename: /etc/traefik/config.yml
        watch: true
################################################################
# Traefik Logging
################################################################
log:
    level: DEBUG

accessLog: {}
################################################################
# Traefik Healthcheck
################################################################
ping: {}
################################################################
# Entrypoints
################################################################
entryPoints:
    web:
        address: ":80"
        http2:
            maxConcurrentStreams: 500