version: "2.7"

server:
    command: "php /var/www/html/bin/console app:run-temporal-worker --no-debug"

rpc:
    listen: tcp://127.0.0.1:6001

logs:
    mode: development
    channels:
        http:
            level: debug
        server:
            mode: raw
            level: info

reload:
    enabled: true
    interval: 1s
    patterns: [".php", ".yaml"]
    services:
        http:
            recursive: true
            ignore: [ "/var/www/html/vendor", "/var/www/html/var"]
            dirs: ["."]

metrics:
    address: "0.0.0.0:9180"

temporal:
    address: "temporal:7233"
    activities:
        num_workers: 4
