version: "2.7"

server:
    command: "php public/index.php"
    env:
        - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
        - APP_ENV: dev

rpc:
    listen: tcp://127.0.0.1:6001

grpc:
    listen: "tcp://127.0.0.1:9001"
    proto:
        - "src/Grpc/Proto/Order/order.proto"

http:
    address: 0.0.0.0:80
    middleware: [ "static", "gzip" ]
    uploads:
        forbid: [ ".php", ".exe", ".bat" ]
    static:
        dir: "public"
        forbid: [ ".php", ".htaccess" ]

status:
    address: localhost:2114

logs:
    mode: development
    channels:
        http:
            level: debug
        server:
            mode: raw
            level: info

reload:
    enabled: true
    interval: 1s
    patterns: [".php", ".yaml"]
    services:
        http:
            recursive: true
            ignore: [ "/var/www/html/vendor", "/var/www/html/var"]
            dirs: ["."]

metrics:
    address: "0.0.0.0:9180"
